In [4]:
import torch

In [5]:
torch.__version__

'2.0.1+cpu'

In [7]:
t1 = torch.tensor([1,2,3,4,5], dtype = torch.float32)
t1

tensor([1., 2., 3., 4., 5.])

In [9]:
# 미분을 통해 수정되는 텐서노드
t2 = torch.tensor(2.0, dtype = torch.float32, requires_grad = True)
t2

tensor(2., requires_grad=True)

In [10]:
t3 = torch.FloatTensor([1,2,3,4,5])
t3

tensor([1., 2., 3., 4., 5.])

In [11]:
t4 = torch.IntTensor([1,2,3,4,5])
t4

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [12]:
t4.numpy()

array([1, 2, 3, 4, 5])

In [13]:
t5 = torch.IntTensor(10) # scalar 노드면 item()
t5.numpy()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## 연산

In [15]:
a = torch.tensor(5)
b = torch.tensor([1,2,3])
type(a)

torch.Tensor

In [16]:
c = torch.add(a,b)
c

tensor([6, 7, 8])

In [18]:
d = a.add(b)
d

tensor([6, 7, 8])

In [19]:
e = a + b
e

tensor([6, 7, 8])

## 인덱싱 슬라이싱

In [21]:
t = torch.tensor([11,22,33,44,55])
t

tensor([11, 22, 33, 44, 55])

In [22]:
t[0].item()

11

In [23]:
t[-1]

tensor(55)

In [24]:
t[1:3]

tensor([22, 33])

## 연산함수 속성

In [26]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[3],[4]])

In [27]:
m1.shape

torch.Size([2, 2])

In [28]:
m2.shape

torch.Size([2, 1])

In [30]:
m1.dim()

2

In [32]:
m1.sub(m2)

tensor([[-2., -1.],
        [-1.,  0.]])

In [33]:
m1.mul(m2)

tensor([[ 3.,  6.],
        [12., 16.]])

In [35]:
# 행렬곱
m1.matmul(m2)

tensor([[11.],
        [25.]])

## 통계함수

In [38]:
m1.mean(dim = 0), m1.mean(dim = 1)

(tensor([2., 3.]), tensor([1.5000, 3.5000]))

In [39]:
m1.sum()

tensor(10.)