In [3]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data/cars.csv', index_col = 'Unnamed: 0')
df

speed  dist
1       4     2
2       4    10
3       7     4
4       7    22
5       8    16
6       9    10
7      10    18
8      10    26
9      10    34
10     11    17
11     11    28
12     12    14
13     12    20
14     12    24
15     12    28
16     13    26
17     13    34
18     13    34
19     13    46
20     14    26
21     14    36
22     14    60
23     14    80
24     15    20
25     15    26
26     15    54
27     16    32
28     16    40
29     17    32
30     17    40
31     17    50
32     18    42
33     18    56
34     18    76
35     18    84
36     19    36
37     19    46
38     19    68
39     20    32
40     20    48
41     20    52
42     20    56
43     20    64
44     22    66
45     23    54
46     24    70
47     24    92
48     24    93
49     24   120
50     25    85

In [10]:
x = torch.FloatTensor(df[['speed']].values)
y = torch.FloatTensor(df[['dist']].values)

In [11]:
linear = Linear(1,1) # w:1X1, b:1, hx = w*x + b
print(list(linear.parameters()))

[Parameter containing:
tensor([[-0.3540]], requires_grad=True), Parameter containing:
tensor([-0.9763], requires_grad=True)]


In [12]:
linear(torch.FloatTensor([[15]]))

tensor([[-6.2865]], grad_fn=<AddmmBackward0>)

In [13]:
linear.forward(torch.FloatTensor([[15],[20]]))

tensor([[-6.2865],
        [-8.0565]], grad_fn=<AddmmBackward0>)

In [14]:
## 

In [15]:
linear = Linear(1,1)
model = Sequential()
model.add_module('nn1', linear)

loss_fn = MSELoss()
optimizer = Adam(linear.parameters(), lr = 0.1)

for step in range(1000):
    optimizer.zero_grad()
    hx = model(x) # w * x + b
    cost = loss_fn(hx, y)
    cost.backward()
    optimizer.step()
    print(step, cost.item())

0 1535.2255859375
1 1415.48291015625
2 1301.844482421875
3 1194.4058837890625
4 1093.244873046875
5 998.4173583984375
6 909.9570922851562
7 827.8724975585938
8 752.14404296875
9 682.7232055664062
10 619.52978515625
11 562.4508056640625
12 511.3387145996094
13 466.0115966796875
14 426.2518615722656
15 391.8077697753906
16 362.3941650390625
17 337.6948547363281
18 317.3656005859375
19 301.038330078125
20 288.3259582519531
21 278.8282470703125
22 272.13800048828125
23 267.848388671875
24 265.5596618652344
25 264.8863830566406
26 265.4639892578125
27 266.9550476074219
28 269.0539245605469
29 271.4911804199219
30 274.0359191894531
31 276.49737548828125
32 278.7247314453125
33 280.606201171875
34 282.0663757324219
35 283.0630798339844
36 283.5837097167969
37 283.6405944824219
38 283.26629638671875
39 282.50909423828125
40 281.4281921386719
41 280.0894775390625
42 278.56182861328125
43 276.9132385253906
44 275.2083740234375
45 273.50604248046875
46 271.8574523925781
47 270.3052978515625
48 26

In [16]:
model(torch.FloatTensor([[15],[20]]))

tensor([[41.5794],
        [60.8254]], grad_fn=<AddmmBackward0>)

In [17]:
model.forward(torch.FloatTensor([[15],[20]]))

tensor([[41.5794],
        [60.8254]], grad_fn=<AddmmBackward0>)