In [1]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('data/test.csv', header = None)
df.columns = ['q1','q2','mid','final']
df

q1  q2  mid  final
0   73  80   75    152
1   93  88   93    185
2   89  91   90    180
3   96  98  100    196
4   73  66   70    142
5   53  46   55    101
6   69  74   77    149
7   47  56   60    115
8   87  79   90    175
9   79  70   88    164
10  69  70   73    141
11  70  65   74    141
12  93  95   91    184
13  79  80   73    152
14  70  73   78    148
15  93  89   96    192
16  78  75   68    147
17  81  90   93    183
18  88  92   86    177
19  78  83   77    159
20  82  86   90    177
21  86  82   89    175
22  78  83   85    175
23  76  83   71    149
24  96  93   95    192

In [6]:
x_data = df.iloc[:,:-1].values
y_data = df.iloc[:,-1].values
x = torch.FloatTensor(x_data)
y = torch.FloatTensor(y_data)

In [7]:
model = Sequential()
model.add_module('nn1', Linear(3,1))
loss_fn = MSELoss()
optimizer = Adam(model.parameters(), lr = 0.1)

In [8]:
for epoch in range(1000):
    optimizer.zero_grad()
    hx = model(x) # hx = torch.matmul(x, w) + b
    cost = loss_fn(hx, y)
    cost.backward()
    optimizer.step()
    print('cost:', cost.item())

C:\Users\NT551XCJ\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\loss.py:536: UserWarning: Using a target size (torch.Size([25])) that is different to the input size (torch.Size([25, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


cost: 31345.779296875
cost: 23466.650390625
cost: 16813.810546875
cost: 11394.8779296875
cost: 7195.376953125
cost: 4170.76953125
cost: 2237.922119140625
cost: 1268.1614990234375
cost: 1085.526611328125
cost: 1474.433349609375
cost: 2199.093505859375
cost: 3032.03369140625
cost: 3783.560302734375
cost: 4322.5234375
cost: 4582.94189453125
cost: 4557.5849609375
cost: 4283.7001953125
cost: 3826.38037109375
cost: 3263.20361328125
cost: 2671.73095703125
cost: 2120.18798828125
cost: 1661.0943603515625
cost: 1327.5882568359375
cost: 1132.236572265625
cost: 1068.2254638671875
cost: 1112.72412109375
cost: 1231.9990234375
cost: 1387.5545654296875
cost: 1542.3402099609375
cost: 1666.0194091796875
cost: 1738.5181884765625
cost: 1751.458984375
cost: 1707.54736328125
cost: 1618.3353271484375
cost: 1500.9847412109375
cost: 1374.6923828125
cost: 1257.3636474609375
cost: 1162.97705078125
cost: 1099.933349609375
cost: 1070.4979248046875
cost: 1071.300048828125
cost: 1094.6827392578125
cost: 1130.5942382

In [10]:
list(model[0].parameters())

[Parameter containing:
 tensor([[0.0537, 0.3971, 1.2664]], requires_grad=True),
 Parameter containing:
 tensor([20.3172], requires_grad=True)]

In [11]:
list(model.parameters())

[Parameter containing:
 tensor([[0.0537, 0.3971, 1.2664]], requires_grad=True),
 Parameter containing:
 tensor([20.3172], requires_grad=True)]

In [15]:
model[0].weight

Parameter containing:
tensor([[0.0537, 0.3971, 1.2664]], requires_grad=True)

In [13]:
# q1 : 90, q2 : 90, mid : 80 예측값을 구하시오

In [20]:
model.forward(torch.FloatTensor([[90,90,80]]))

tensor([[162.2015]], grad_fn=<AddmmBackward0>)

In [ ]:
### low level

In [ ]:
x_data = df.iloc[:,:-1].values
y_data = df.iloc[:,-1].values
x = torch.FloatTensor(x_data)
y = torch.FloatTensor(y_data)

In [21]:
w = torch.empty([3,1], requires_grad = True)
b = torch.empty([1], requires_grad = True)
torch.nn.init.uniform_(w)
torch.nn.init.uniform_(b)

tensor([0.9483], requires_grad=True)

In [22]:
def cost():
    hx = torch.matmul(x,w) + b
    c = torch.mean((hx - y)**2)
    return c

In [23]:
optimizer = Adam([w,b], lr = 0.01)
for epoch in range(2000):
    c = cost()
    optimizer.zero_grad()
    c.backward()
    optimizer.step()
    print('cost:', c.item())

cost: 7863.1953125
cost: 7468.40478515625
cost: 7085.8046875
cost: 6715.59375
cost: 6357.95263671875
cost: 6013.03662109375
cost: 5680.98193359375
cost: 5361.89697265625
cost: 5055.86328125
cost: 4762.9345703125
cost: 4483.13818359375
cost: 4216.46728515625
cost: 3962.886474609375
cost: 3722.3271484375
cost: 3494.687255859375
cost: 3279.83544921875
cost: 3077.604736328125
cost: 2887.7958984375
cost: 2710.177490234375
cost: 2544.4873046875
cost: 2390.43310546875
cost: 2247.690673828125
cost: 2115.910400390625
cost: 1994.7161865234375
cost: 1883.708251953125
cost: 1782.46337890625
cost: 1690.5426025390625
cost: 1607.48681640625
cost: 1532.825927734375
cost: 1466.0791015625
cost: 1406.757568359375
cost: 1354.369140625
cost: 1308.421142578125
cost: 1268.423583984375
cost: 1233.8919677734375
cost: 1204.3505859375
cost: 1179.3360595703125
cost: 1158.3990478515625
cost: 1141.1082763671875
cost: 1127.0506591796875
cost: 1115.83544921875
cost: 1107.09423828125
cost: 1100.4830322265625
cost: 109

In [24]:
def hxFn(xd):
    xd = torch.FloatTensor(xd)
    hx = torch.matmul(xd, w) + b
    return hx.detach().numpy()

In [25]:
hxFn([[80,90,90]])

array([[170.48016]], dtype=float32)