In [1]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential,CrossEntropyLoss, Softmax
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
x = torch.FloatTensor([[1,3],[2,2],[3,1],[4,6],[5,5],[6,4]])
y = torch.FloatTensor([[0],[0],[0],[1],[1],[1]])

In [3]:
df = pd.read_csv('data/softmax.txt', sep = ' ', header = None)
df

0  1  2  3  4
0  2  1  0  0  1
1  3  2  0  0  1
2  3  4  0  0  1
3  5  5  0  1  0
4  7  5  0  1  0
5  2  5  0  1  0
6  6  6  1  0  0
7  7  7  1  0  0

In [4]:
x_data = df.iloc[:,0:2]
y_data = df.iloc[:,2:]

In [5]:
x = torch.FloatTensor(x_data.values)
y = torch.FloatTensor(y_data.values)

In [9]:
s = torch.nn.Softmax()
s1 = torch.nn.Softmax(dim = 1)
rdata = torch.randn(2,3)
rdata

tensor([[ 1.5843,  2.0073,  0.5414],
        [-1.3457,  0.0833,  1.0457]])

In [10]:
s(rdata)

C:\Users\NT551XCJ\AppData\Local\Temp\ipykernel_6516\963531194.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  s(rdata)


tensor([[0.3473, 0.5302, 0.1224],
        [0.0621, 0.2592, 0.6787]])

In [11]:
s1(rdata)

tensor([[0.3473, 0.5302, 0.1224],
        [0.0621, 0.2592, 0.6787]])

In [12]:
model = Sequential()
model.add_module('nn1', Linear(2,3))
model.add_module('soft1', Softmax(dim = 1))
loss_fn = CrossEntropyLoss()
optimizer = Adam(model.parameters(), lr = 0.01)

In [13]:
for step in range(2000):
    optimizer.zero_grad()
    hx = model(x) # z = matmul(x, w) + b => hx = softmax(z)
    cost = loss_fn(hx, y)
    cost.backward()
    optimizer.step()
    print(step, cost.item())

0 1.1921048164367676
1 1.1895177364349365
2 1.187011480331421
3 1.1846742630004883
4 1.1825690269470215
5 1.1807342767715454
6 1.1791846752166748
7 1.1779135465621948
8 1.1768968105316162
9 1.1760988235473633
10 1.1754778623580933
11 1.174992322921753
12 1.1746039390563965
13 1.1742801666259766
14 1.1739938259124756
15 1.1737236976623535
16 1.1734528541564941
17 1.1731672286987305
18 1.1728553771972656
19 1.17250657081604
20 1.1721110343933105
21 1.1716587543487549
22 1.1711392402648926
23 1.1705411672592163
24 1.1698521375656128
25 1.169057846069336
26 1.1681429147720337
27 1.1670894622802734
28 1.165878176689148
29 1.1644877195358276
30 1.16289484500885
31 1.1610753536224365
32 1.1590044498443604
33 1.1566579341888428
34 1.1540145874023438
35 1.1510579586029053
36 1.1477811336517334
37 1.1441903114318848
38 1.1403095722198486
39 1.1361838579177856
40 1.1318800449371338
41 1.1274808645248413
42 1.1230740547180176
43 1.1187329292297363
44 1.1144946813583374
45 1.1103397607803345
46 1.1

In [18]:
model(torch.FloatTensor([[5,6],[2,1]])).argmax(axis = 1)

tensor([1, 2])