아버지와 아들키

- 아버지 키가 170인경우 아들키 예측
- train, test
- 정규화
- (케라스 버전)
- 파이프라인
- 그냥 (파이토치 하이레벨) 

In [86]:
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from scikeras.wrappers import KerasRegressor
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [73]:
df_train = pd.read_excel("아버지아들키.xlsx",sheet_name=0)
df_test = pd.read_excel("아버지아들키.xlsx",sheet_name=1)

In [74]:
df_train.head()

Father      Son
0  165.100  151.892
1  165.100  160.782
2  167.132  159.512
3  155.194  163.322
4  160.020  163.068

In [75]:
df_train.shape, df_test.shape

((755, 2), (323, 2))

In [76]:
X_train = df_train[['Father']]
X_test = df_test[['Father']]
y_train = df_train[['Son']]
y_test = df_test[['Son']]

# 파이프라인

In [79]:
def createModel():
    dense = Dense( units=1, input_dim=1)
    model = Sequential( [dense] )
    model.compile( loss='mse', optimizer=Adam( 0.1) )
    return model

In [80]:
kcf = KerasRegressor(model=createModel , epochs=1000, verbose=1 )

In [87]:
pmodel = make_pipeline( StandardScaler(), kcf)
pmodel.fit( X_train, y_train )

Epoch 1/1000
24/24 [==============================] - 0s 1ms/step - loss: 30038.4590
Epoch 2/1000
24/24 [==============================] - 0s 1ms/step - loss: 29213.7852
Epoch 3/1000
24/24 [==============================] - 0s 1ms/step - loss: 28406.7520
Epoch 4/1000
24/24 [==============================] - 0s 1ms/step - loss: 27616.1914
Epoch 5/1000
24/24 [==============================] - 0s 3ms/step - loss: 26840.1289
Epoch 6/1000
24/24 [==============================] - 0s 1ms/step - loss: 26082.3730
Epoch 7/1000
24/24 [==============================] - 0s 1ms/step - loss: 25341.3809
Epoch 8/1000
24/24 [==============================] - 0s 1ms/step - loss: 24614.8398
Epoch 9/1000
24/24 [==============================] - 0s 1ms/step - loss: 23904.6250
Epoch 10/1000
24/24 [==============================] - 0s 1ms/step - loss: 23210.6387
Epoch 11/1000
24/24 [==============================] - 0s 1ms/step - loss: 22535.0508
Epoch 12/1000
24/24 [==============================] - 0s 1ms/s

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('kerasregressor',
                 KerasRegressor(epochs=1000, model=<function createModel at 0x0000022BCB1F9B40>))])

In [89]:
pmodel.predict([[170.0]])

1/1 [==============================] - 0s 21ms/step


C:\Users\NT551XCJ\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[173.52641]], dtype=float32)

In [90]:
pred_train = pmodel.predict( X_train)
pred_test = pmodel.predict(X_test)

11/11 [==============================] - 0s 919us/step


In [91]:
print(r2_score(y_train, pred_train))
print(r2_score(y_test, pred_test))

0.2492900345973712
0.2524582240216704


# 케라스 그냥

In [92]:
# 정규화
X = pd.concat([X_train, X_test])
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [94]:
X_train = X[:755]
X_test = X[755:]

In [95]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((755, 1), (323, 1), (755, 1), (323, 1))

In [96]:
dense = Dense(units = 1, input_dim = 1)

model_ = Sequential([dense])
model_.compile(loss = "mse", optimizer = Adam(learning_rate = 0.01))
model_.fit(X_train, y_train, epochs = 1000)


Epoch 1/1000
24/24 [==============================] - 0s 1ms/step - loss: 30400.4629
Epoch 2/1000
24/24 [==============================] - 0s 1ms/step - loss: 30316.5430
Epoch 3/1000
24/24 [==============================] - 0s 1ms/step - loss: 30233.1699
Epoch 4/1000
24/24 [==============================] - 0s 1ms/step - loss: 30150.0605
Epoch 5/1000
24/24 [==============================] - 0s 1ms/step - loss: 30067.0352
Epoch 6/1000
24/24 [==============================] - 0s 1ms/step - loss: 29984.5215
Epoch 7/1000
24/24 [==============================] - 0s 1ms/step - loss: 29901.1660
Epoch 8/1000
24/24 [==============================] - 0s 1ms/step - loss: 29818.5215
Epoch 9/1000
24/24 [==============================] - 0s 1ms/step - loss: 29736.1484
Epoch 10/1000
24/24 [==============================] - 0s 1ms/step - loss: 29653.9473
Epoch 11/1000
24/24 [==============================] - 0s 1ms/step - loss: 29571.7227
Epoch 12/1000
24/24 [==============================] - 0s 1ms/s

In [98]:
model_.predict(scaler.transform([[170.0]]))

1/1 [==============================] - 0s 38ms/step


C:\Users\NT551XCJ\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[173.39319]], dtype=float32)

In [100]:
pred_train_ = model_.predict(X_train)
pred_test_ = model_.predict(X_test)

print(r2_score(y_train, pred_train_))
print(r2_score(y_test, pred_test_))

11/11 [==============================] - 0s 1ms/step
0.24966458035312855
0.25188174524873896


# 파이토치

In [101]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [102]:
df_train = pd.read_excel("아버지아들키.xlsx",sheet_name=0)
df_test = pd.read_excel("아버지아들키.xlsx",sheet_name=1)

In [103]:
X_train = df_train[['Father']]
X_test = df_test[['Father']]
y_train = df_train[['Son']]
y_test = df_test[['Son']]

In [104]:
X = pd.concat([X_train, X_test])
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [105]:
X_train = X[:755]
X_test = X[755:]

In [106]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((755, 1), (323, 1), (755, 1), (323, 1))

In [118]:
y_train.to_numpy()

array([[151.892],
       [160.782],
       [159.512],
       [163.322],
       [163.068],
       [162.56 ],
       [164.084],
       [162.56 ],
       [165.608],
       [166.116],
       [166.878],
       [166.116],
       [165.862],
       [165.1  ],
       [166.37 ],
       [165.354],
       [165.354],
       [169.164],
       [168.656],
       [167.894],
       [167.64 ],
       [168.91 ],
       [166.878],
       [167.386],
       [167.386],
       [168.91 ],
       [168.402],
       [167.894],
       [168.402],
       [168.656],
       [170.18 ],
       [169.672],
       [176.022],
       [156.718],
       [166.878],
       [175.26 ],
       [171.196],
       [170.688],
       [171.704],
       [171.45 ],
       [169.926],
       [171.704],
       [170.688],
       [169.672],
       [170.688],
       [171.45 ],
       [171.196],
       [171.704],
       [170.942],
       [169.672],
       [169.418],
       [169.926],
       [171.704],
       [172.72 ],
       [173.99 ],
       [17

In [115]:
X_train = torch.FloatTensor(X_train)

In [119]:
linear = Linear(in_features = 1, out_features =  1) # w : 1x1 , b : 1 , hx = w*x +b
model_py = Sequential()
model_py.add_module('nn1', linear)
loss_fn = MSELoss()
optimizer = Adam(model_py.parameters(), lr = 0.1)

for step in range(1000):
    optimizer.zero_grad()
    hx = model_py(X_train) # w*x + b / linear(x)
    cost = loss_fn(hx, y_train.to_numpy()) # 이게달라짐
    cost.backward()
    optimizer.step()
    print(step, cost.item())

TypeError: 'int' object is not callable