In [13]:
import pandas as pd
import numpy as np
import sklearn
import tensorflow as tf

# 0. Tensor Flow 기본 구성

## [1] Scalar Data

In [14]:
s1 = 10
s2 = 3.14
s3 = 'abc'

## [2] Vector Data

In [15]:
v = [10,20,30]

## [3] Matrix Data

In [16]:
m = [[10,20,30], [10,20,30]]

## [4] 3D tensor

In [17]:
d3 = [[[10,20,30], [10,20,30]], [[10,20,30], [10,20,30]]]

## [5] 4D tensor   

In [18]:
d4 = [[[[10,20,30], [10,20,30]], [[10,20,30], [10,20,30]]],
[[[10,20,30], [10,20,30]], [[10,20,30], [10,20,30]]]]

In [19]:
type(d4)

list

## [5] 텐서 데이터 노드 정의하는 방법
- constant : 읽기 전용
- variable : 읽기 쓰기

In [20]:
s1 = 10
c1 = tf.constant(s1)
c1

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [21]:
print(type(c1))

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [22]:
c1.numpy()

10

In [23]:
v1.numpy()

array([10, 20, 30])

## [6] 연산 : 산술관련 연산자 (numpy, pandas, tensor)
- element wise : 요소별 연산 (동일한 인덱스)
- broad cast : 연산 대상에서 자동 확장

In [24]:
a = tf.constant(3)
b = tf.constant([1,2,3])
c = tf.multiply(a, b) # [3,3,3] * [1,2,3] : 스칼라값인 3이 자동 확장(브로드 캐스팅) 됨
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9])>

In [25]:
a * b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9])>

## [7] tensorboard 툴을 이용하여 메모리 그래프 상태 확인이 가능함

In [31]:
d = tf.add(a,b) # a + b
d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>

In [32]:
d.numpy()

array([4, 5, 6])

In [34]:
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9])>

In [33]:
e = c+d
e

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 7, 11, 15])>

In [36]:
f = tf.constant([1,2,3])
g = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
h = f + g
h

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])>

In [38]:
i = tf.constant([[1],[2],[3]])
j = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
k = i * j
k

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])>

In [40]:
i = tf.constant([[1],[2],[3]])
j = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
k = tf.multiply(i,j)
k

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])>

## [8] 행렬곱

In [41]:
o = tf.constant([[1,2],[3,4]])
p = tf.constant([[5,6],[7,8]])
q = tf.multiply(o,p) # O X P
r = tf.matmul(o,p)

In [42]:
q

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [43]:
r

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [47]:
o = tf.constant([[1,2],[3,4]])
p = tf.constant([[5,6],[6,8]])
q = tf.divide(p,o)
q

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5., 3.],
       [2., 2.]])>

### [9] 자주 사용하는 함수

In [48]:
# square
s = [1,2,3]
t = tf.square(s)
t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9])>

In [49]:
# reduce_mean
s = [1,2,3]
u = tf.reduce_mean(s)
u

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [57]:
# reduce_sum
s = [[1,2,3],[4,5,6]]
v = tf.reduce_mean(s)
v

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [59]:
### variable
v = tf.Variable(10)
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [60]:
type(v)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [61]:
## variable은 assign을 통해서 객체에 계산을 할 수 있다.
v.assign_sub(2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=8>