In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow.keras.optimizers import Adam
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [2]:
df = pd.read_csv('data/test.csv', header = None)
df.columns = ['q1', 'q2', 'mid', 'final']
df

q1  q2  mid  final
0   73  80   75    152
1   93  88   93    185
2   89  91   90    180
3   96  98  100    196
4   73  66   70    142
5   53  46   55    101
6   69  74   77    149
7   47  56   60    115
8   87  79   90    175
9   79  70   88    164
10  69  70   73    141
11  70  65   74    141
12  93  95   91    184
13  79  80   73    152
14  70  73   78    148
15  93  89   96    192
16  78  75   68    147
17  81  90   93    183
18  88  92   86    177
19  78  83   77    159
20  82  86   90    177
21  86  82   89    175
22  78  83   85    175
23  76  83   71    149
24  96  93   95    192

In [6]:
x_data = df.iloc[:,:-1].values
y_data = df.iloc[:,-1].values

In [9]:
x_data.shape

(25, 3)

In [7]:
dense = Dense(units = 1, input_dim = 3) # w : 3 X 1, b : 1

In [8]:
dense(x_data) # hx = matmul(x_data, w) + b

<tf.Tensor: shape=(25, 1), dtype=float32, numpy=
array([[-74.49487 ],
       [-95.01873 ],
       [-90.924774],
       [-97.4854  ],
       [-75.09892 ],
       [-53.63069 ],
       [-69.140755],
       [-45.74015 ],
       [-88.19165 ],
       [-78.773094],
       [-69.82938 ],
       [-70.68146 ],
       [-95.61978 ],
       [-82.06863 ],
       [-70.10694 ],
       [-94.445206],
       [-81.734024],
       [-80.73101 ],
       [-90.56063 ],
       [-80.156075],
       [-82.414345],
       [-87.28252 ],
       [-78.5506  ],
       [-78.969376],
       [-98.34619 ]], dtype=float32)>

In [10]:
w, b = dense.get_weights()
w, b

(array([[-1.1953979 ],
        [-0.02852678],
        [ 0.20068419]], dtype=float32),
 array([0.], dtype=float32))

In [11]:
dense = Dense(units = 1, input_dim = 3) # w : 3 X 1, b : 1
model = Sequential([dense])
model.compile(loss = 'mse', optimizer = Adam(0.1))
model.fit(x_data, y_data, epochs = 500)

Epoch 1/500
1/1 [==============================] - 0s 335ms/step - loss: 52397.0234
Epoch 2/500
1/1 [==============================] - 0s 0s/step - loss: 41848.9492
Epoch 3/500
1/1 [==============================] - 0s 11ms/step - loss: 32525.5801
Epoch 4/500
1/1 [==============================] - 0s 0s/step - loss: 24440.4082
Epoch 5/500
1/1 [==============================] - 0s 0s/step - loss: 17594.3496
Epoch 6/500
1/1 [==============================] - 0s 17ms/step - loss: 11971.8867
Epoch 7/500
1/1 [==============================] - 0s 0s/step - loss: 7537.4346
Epoch 8/500
1/1 [==============================] - 0s 16ms/step - loss: 4231.5156
Epoch 9/500
1/1 [==============================] - 0s 0s/step - loss: 1967.4792
Epoch 10/500
1/1 [==============================] - 0s 17ms/step - loss: 629.9701
Epoch 11/500
1/1 [==============================] - 0s 0s/step - loss: 76.0525
Epoch 12/500
1/1 [==============================] - 0s 16ms/step - loss: 140.1160
Epoch 13/500
1/1 [====

In [13]:
#dense(x_data)
model.predict(x_data)

1/1 [==============================] - 0s 92ms/step


array([[156.39627],
       [183.21475],
       [182.92719],
       [198.72314],
       [139.16019],
       [101.67001],
       [149.65327],
       [112.25282],
       [169.72205],
       [155.94803],
       [143.28087],
       [139.11574],
       [189.29915],
       [157.80322],
       [149.60841],
       [185.9339 ],
       [149.41556],
       [180.20886],
       [181.28296],
       [162.72337],
       [174.82167],
       [171.82704],
       [167.22763],
       [158.50085],
       [190.75766]], dtype=float32)

In [15]:
from sklearn.metrics import r2_score

r2_score(y_data, model.predict(x_data))

1/1 [==============================] - 0s 21ms/step


0.9660945323684867

In [ ]:
class MyDense:
    def __init__(self, units = nlabel, input_dim = nfeature):
        self.w = tf.random.uniform([nfeature, nlabel])
        self.b = tf.random.uniform([nlabel])
    def __call__(self, xdata):
        print('call', xdata)
        hx = tf.matmul(xdata, self.w) + self.b
        return hx
    def __self__(repr):
        print('test')
    def get_weights(self):
        return self.w, self.b