In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.optimizers import Adam

In [2]:
x_data = np.array([[1,3], [2,2], [3,1], [4,6], [5,5], [6,4]])
y_data = np.array([[0],[0],[0],[1],[1],[1]])

In [3]:
x = tf.constant(x_data,tf.float32)
y = tf.constant(y_data,tf.float32)

In [4]:
# 초기화 : xavier, he (최적 초기화 알고리즘)
initX = tf.initializers.GlorotUniform()
w = tf.Variable(initX(shape = [2,1]))
b = tf.Variable(initX(shape = [1]))

C:\Users\NT551XCJ\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\initializers\initializers.py:120: UserWarning: The initializer GlorotUniform is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(


In [17]:
def compute_loss():
    z = tf.matmul(x, w) + b
    #hx = tf.nn.sigmoid(z)
    cost_i = tf.nn.sigmoid_cross_entropy_with_logits(labels = y, logits = z)
    print('cost_i:', cost_i)
    cost = tf.reduce_mean(cost_i)
    return cost

In [18]:
optimizer = Adam(0.1)
for i in range(1000):
    optimizer.minimize(compute_loss, var_list = [w,b])
    print(i, 'cost:', compute_loss().numpy())
    

cost_i: tf.Tensor(
[[0.00404742]
 [0.00410823]
 [0.00416995]
 [0.00176747]
 [0.00174128]
 [0.00171547]], shape=(6, 1), dtype=float32)
cost_i: tf.Tensor(
[[0.00543506]
 [0.00551506]
 [0.00559624]
 [0.00072774]
 [0.00071716]
 [0.00070673]], shape=(6, 1), dtype=float32)
0 cost: 0.0031163336
cost_i: tf.Tensor(
[[0.00543506]
 [0.00551506]
 [0.00559624]
 [0.00072774]
 [0.00071716]
 [0.00070673]], shape=(6, 1), dtype=float32)
cost_i: tf.Tensor(
[[0.00374316]
 [0.00379378]
 [0.00384507]
 [0.0016058 ]
 [0.00158435]
 [0.00156319]], shape=(6, 1), dtype=float32)
1 cost: 0.0026892272
cost_i: tf.Tensor(
[[0.00374316]
 [0.00379378]
 [0.00384507]
 [0.0016058 ]
 [0.00158435]
 [0.00156319]], shape=(6, 1), dtype=float32)
cost_i: tf.Tensor(
[[0.00278884]
 [0.00282143]
 [0.00285439]
 [0.00292393]
 [0.00289016]
 [0.00285679]], shape=(6, 1), dtype=float32)
2 cost: 0.0028559223
cost_i: tf.Tensor(
[[0.00278884]
 [0.00282143]
 [0.00285439]
 [0.00292393]
 [0.00289016]
 [0.00285679]], shape=(6, 1), dtype=float32)

In [10]:
w.numpy()

array([[1.9816338],
       [1.9666904]], dtype=float32)

In [15]:
def hxfn(xd):
    xd = np.float32(xd)
    z = tf.matmul(xd, w) + b
    hx = tf.nn.sigmoid(z)
    return z.numpy(), hx.numpy(), (hx.numpy() > 0.5) + 0

In [16]:
hxfn([[5,5]])

(array([[6.3522644]], dtype=float32),
 array([[0.99826026]], dtype=float32),
 array([[1]]))