In [5]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.optimizers import Adam

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

from tensorflow.keras.optimizers import Adam
from sklearn.metrics import accuracy_score

In [7]:
df = pd.read_csv('data/softmax.txt', sep = ' ', header = None)
df

0  1  2  3  4
0  2  1  0  0  1
1  3  2  0  0  1
2  3  4  0  0  1
3  5  5  0  1  0
4  7  5  0  1  0
5  2  5  0  1  0
6  6  6  1  0  0
7  7  7  1  0  0

In [8]:
x_data = df.iloc[:,:2]
y_data = df.iloc[:,2:]

In [9]:
x = tf.constant(x_data, tf.float32)
y = tf.constant(y_data, tf.float32)

In [10]:
initX = tf.initializers.GlorotUniform()
w = tf.Variable(initX(shape = [2,3]))
b = tf.Variable(initX(shape = [3]))

C:\Users\NT551XCJ\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\initializers\initializers.py:120: UserWarning: The initializer GlorotUniform is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(


In [11]:
def compute_loss():
    z = tf.matmul(x, w) + b
    cost_i = tf.nn.softmax_cross_entropy_with_logits(labels = y, logits = z)
    c = tf.reduce_mean(cost_i)
    return c

In [13]:
optimizer = Adam(0.1)
for i in range(1000):
    optimizer.minimize(compute_loss, var_list = [w,b])
    print(i, 'cost:', compute_loss().numpy())

0 cost: 2.8873792
1 cost: 2.4385262
2 cost: 1.9960351
3 cost: 1.4824991
4 cost: 1.154102
5 cost: 1.3195529
6 cost: 1.6208409
7 cost: 1.7563282
8 cost: 1.7106178
9 cost: 1.5327663
10 cost: 1.2911685
11 cost: 1.078825
12 cost: 0.99478817
13 cost: 1.0474792
14 cost: 1.1459306
15 cost: 1.2161211
16 cost: 1.231384
17 cost: 1.1917884
18 cost: 1.1105865
19 cost: 1.0109307
20 cost: 0.92589426
21 cost: 0.8888099
22 cost: 0.9059553
23 cost: 0.9451422
24 cost: 0.96628654
25 cost: 0.9506018
26 cost: 0.9050931
27 cost: 0.85434437
28 cost: 0.823889
29 cost: 0.81995714
30 cost: 0.82707924
31 cost: 0.82720566
32 cost: 0.8143483
33 cost: 0.79397
34 cost: 0.77497125
35 cost: 0.7627352
36 cost: 0.75717646
37 cost: 0.7543715
38 cost: 0.7491955
39 cost: 0.7385497
40 cost: 0.72395974
41 cost: 0.7109256
42 cost: 0.7043433
43 cost: 0.70372415
44 cost: 0.7035626
45 cost: 0.6986035
46 cost: 0.688262
47 cost: 0.6764865
48 cost: 0.6680126
49 cost: 0.6644833
50 cost: 0.66366184
51 cost: 0.6619184
52 cost: 0.657243

In [14]:
w.numpy()

array([[ 0.7351251 ,  0.62931126,  0.37514198],
       [ 3.8163335 ,  0.05166244, -3.9169853 ]], dtype=float32)

In [21]:
def hxFn(xd):
    xd = np.float32(xd)
    z = tf.matmul(xd, w) + b
    hx = tf.nn.softmax(z)
    return hx.numpy()

In [22]:
hxFn([[5,6]]).argmax(axis = 1)

array([0], dtype=int64)

In [24]:
arr = np.array([[11,2,6],[30,27,90],[1,2,3]])
arr

array([[11,  2,  6],
       [30, 27, 90],
       [ 1,  2,  3]])

In [25]:
arr.argmax()

5

In [26]:
arr.argmax(axis = 0)

array([1, 1, 1], dtype=int64)

In [27]:
# 2,3과 7,7
hxFn([[2,3],[7,7]]).argmax(axis = 1)

array([2, 0], dtype=int64)

In [28]:
hxFn(x_data)

array([[2.2888379e-14, 1.2278711e-06, 9.9999881e-01],
       [7.4895597e-11, 8.3765110e-05, 9.9991620e-01],
       [3.1617240e-04, 1.8992376e-01, 8.0976003e-01],
       [7.8051411e-02, 8.7933004e-01, 4.2618487e-02],
       [9.6311249e-02, 8.7809008e-01, 2.5598623e-02],
       [5.5300839e-02, 8.5578626e-01, 8.8912874e-02],
       [8.0968797e-01, 1.9017690e-01, 1.3510103e-04],
       [9.9512708e-01, 4.8729130e-03, 5.0739050e-08]], dtype=float32)

In [29]:
hxFn(x_data).argmax(axis = 1)

array([2, 2, 2, 1, 1, 1, 0, 0], dtype=int64)