In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow.keras.optimizers import Adam
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [3]:
df = pd.read_csv('data/softmax.txt', sep = ' ', header = None)
df

0  1  2  3  4
0  2  1  0  0  1
1  3  2  0  0  1
2  3  4  0  0  1
3  5  5  0  1  0
4  7  5  0  1  0
5  2  5  0  1  0
6  6  6  1  0  0
7  7  7  1  0  0

In [4]:
x_data = df.iloc[:,0:2].values
y_data = df.iloc[:,2:].values

In [12]:
x_data.shape

(8, 2)

In [13]:
y_data.shape

(8, 3)

In [7]:
dense = Dense(units = 3, input_dim = 2, activation = 'softmax')

model = Sequential([dense])

model.compile(loss = 'categorical_crossentropy', optimizer = Adam(0.1), metrics = ['acc']  )

model.fit(x_data, y_data, epochs = 1000)

Epoch 1/1000
1/1 [==============================] - 0s 360ms/step - loss: 1.3949 - acc: 0.2500
Epoch 2/1000
1/1 [==============================] - 0s 6ms/step - loss: 1.0637 - acc: 0.3750
Epoch 3/1000
1/1 [==============================] - 0s 6ms/step - loss: 1.1046 - acc: 0.3750
Epoch 4/1000
1/1 [==============================] - 0s 7ms/step - loss: 1.1271 - acc: 0.3750
Epoch 5/1000
1/1 [==============================] - 0s 6ms/step - loss: 1.0142 - acc: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.9624 - acc: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.9708 - acc: 0.6250
Epoch 8/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.9911 - acc: 0.6250
Epoch 9/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.9706 - acc: 0.6250
Epoch 10/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.9337 - acc: 0.5000
Epoch 11/1000
1/1 [==============================] - 0s 6ms/step - 

In [11]:
model.predict(x_data)

1/1 [==============================] - 0s 21ms/step


array([[3.88097013e-18, 3.04644487e-08, 1.00000000e+00],
       [1.09595282e-13, 5.92166361e-06, 9.99994040e-01],
       [3.89687921e-05, 1.20986395e-01, 8.78974676e-01],
       [4.76762503e-02, 9.25201356e-01, 2.71223430e-02],
       [5.78362010e-02, 9.25473630e-01, 1.66902170e-02],
       [3.50977629e-02, 9.09637511e-01, 5.52646816e-02],
       [8.82146776e-01, 1.17835470e-01, 1.77711026e-05],
       [9.99081373e-01, 9.18613630e-04, 7.12718107e-10]], dtype=float32)

In [8]:
model.predict(x_data).argmax(axis = 1)

1/1 [==============================] - 0s 99ms/step


array([2, 2, 2, 1, 1, 1, 0, 0], dtype=int64)

In [9]:
y_data.argmax(axis = 1)

array([2, 2, 2, 1, 1, 1, 0, 0], dtype=int64)

In [10]:
model.predict([[5,5]])

1/1 [==============================] - 0s 76ms/step


array([[0.04767625, 0.92520136, 0.02712234]], dtype=float32)