In [2]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Dense, SimpleRNN, LSTM, GRU 
# SimpleRNN -> LSTM (계산이 너무 복잡) -> GRU (계산 간소화, LSTM 정도의 성능) 
from tensorflow.keras import Sequential



In [8]:
x = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]], np.float32)
y = np.array([4,5,6,7])
x.shape

(4, 3)

In [11]:
x = x.reshape(4,3,1) # (batchsize, sequence Length, 특성 데이터 갯수)
x

array([[[1.],
        [2.],
        [3.]],

       [[2.],
        [3.],
        [4.]],

       [[3.],
        [4.],
        [5.]],

       [[4.],
        [5.],
        [6.]]], dtype=float32)

In [13]:
model = Sequential()
model.add(SimpleRNN(32, activation = 'relu', input_shape = (3,1)))

model.add(Dense(units = 32))

model.add(Dense(units = 1))

model.compile(loss = 'mse', optimizer = 'adam')

model.fit(x, y, epochs = 100)

Epoch 1/100
1/1 [==============================] - 1s 922ms/step - loss: 38.6205
Epoch 2/100
1/1 [==============================] - 0s 3ms/step - loss: 34.7163
Epoch 3/100
1/1 [==============================] - 0s 0s/step - loss: 31.0394
Epoch 4/100
1/1 [==============================] - 0s 16ms/step - loss: 27.5877
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: 24.3457
Epoch 6/100
1/1 [==============================] - 0s 13ms/step - loss: 21.3157
Epoch 7/100
1/1 [==============================] - 0s 0s/step - loss: 18.5058
Epoch 8/100
1/1 [==============================] - 0s 13ms/step - loss: 15.9035
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 13.5011
Epoch 10/100
1/1 [==============================] - 0s 0s/step - loss: 11.3136
Epoch 11/100
1/1 [==============================] - 0s 3ms/step - loss: 9.3389
Epoch 12/100
1/1 [==============================] - 0s 11ms/step - loss: 7.5747
Epoch 13/100
1/1 [==============================

In [16]:
model.predict(np.array([7,8,9]).reshape(1,3,1))

1/1 [==============================] - 0s 13ms/step


array([[10.916785]], dtype=float32)

In [38]:
x = np.array([[[1,2],[3,4],[5,6],[7,8]]], np.float32)
x

array([[[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]], dtype=float32)

In [39]:
rnn = SimpleRNN(3, return_sequences = True, input_shape = (4,2))

rnn(x)

<tf.Tensor: shape=(1, 4, 3), dtype=float32, numpy=
array([[[ 0.6279514 , -0.75946915, -0.8838186 ],
        [ 0.98681307, -0.96514636, -0.86131513],
        [ 0.99772644, -0.99002516, -0.9372008 ],
        [ 0.9996173 , -0.9980333 , -0.98638546]]], dtype=float32)>

In [40]:
w = rnn.get_weights()
len(w)

3

In [41]:
w[0].shape # 특성데이터, unit

(2, 3)

In [42]:
w[1].shape # (unit, unit)

(3, 3)

In [43]:
w[2].shape # b

(3,)

In [44]:
y1 = np.tanh(np.matmul(([1,2]), w[0]) + w[2])
y1

array([ 0.62795134, -0.75946918, -0.88381863])

In [53]:
y2 = np.tanh(np.matmul([[3,4]], w[0]) + np.matmul(y1, w[1]) + w[2])
y2

array([[ 0.98681307, -0.96514638, -0.86131517]])

In [54]:
y3 = np.tanh(np.matmul([[5,6]], w[0]) + np.matmul(y2, w[1]) + w[2])
y3

array([[ 0.9977265 , -0.99002512, -0.93720083]])

In [55]:
y4 = np.tanh(np.matmul([[7,8]], w[0]) + np.matmul(y3, w[1]) + w[2])
y4

array([[ 0.99961747, -0.99803337, -0.98638549]])

In [56]:
rnn1 = SimpleRNN(3, input_shape = (4,2))

rnn(x)

<tf.Tensor: shape=(1, 4, 3), dtype=float32, numpy=
array([[[ 0.6279514 , -0.75946915, -0.8838186 ],
        [ 0.98681307, -0.96514636, -0.86131513],
        [ 0.99772644, -0.99002516, -0.9372008 ],
        [ 0.9996173 , -0.9980333 , -0.98638546]]], dtype=float32)>