In [2]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Dense, SimpleRNN, LSTM, GRU, TimeDistributed
# SimpleRNN -> LSTM (계산이 너무 복잡) -> GRU (계산 간소화, LSTM 정도의 성능) 
from tensorflow.keras import Sequential

import pandas as pd

# 1. Many to One

In [3]:
x = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
y = np.array([4,5,6,7])

In [4]:
xR = x.reshape(4,3,1) # batch, timestep, 특성데이터의 수
xR

array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]],

       [[3],
        [4],
        [5]],

       [[4],
        [5],
        [6]]])

In [11]:
model = Sequential()
model.add(SimpleRNN(16, activation = 'tanh', input_shape = (3,1)))

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 16)                288       
                                                                 
Total params: 288 (1.12 KB)
Trainable params: 288 (1.12 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [8]:
model = Sequential()
model.add(LSTM(16, activation = 'tanh', input_shape = (3,1)))

In [9]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_1 (LSTM)               (None, 16)                1152      
                                                                 
Total params: 1152 (4.50 KB)
Trainable params: 1152 (4.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [7]:
model = Sequential()
model.add(GRU(16, activation = 'relu', input_shape = (3,1)))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru (GRU)                   (None, 16)                912       
                                                                 
Total params: 912 (3.56 KB)
Trainable params: 912 (3.56 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model = Sequential()
model.add(GRU(16, activation = 'relu', input_shape = (3,1)))
model.add(Dense(units = 32))
model.add(Dense(units = 16))
model.add(Dense(units = 1))
model.compile(loss = 'mse', optimizer = 'adam')
model.fit(xR, y, epochs = 500)

model.summary()

Epoch 1/500
1/1 [==============================] - 1s 1s/step - loss: 32.8293
Epoch 2/500
1/1 [==============================] - 0s 4ms/step - loss: 31.9403
Epoch 3/500
1/1 [==============================] - 0s 5ms/step - loss: 31.0703
Epoch 4/500
1/1 [==============================] - 0s 5ms/step - loss: 30.2177
Epoch 5/500
1/1 [==============================] - 0s 37ms/step - loss: 29.3811
Epoch 6/500
1/1 [==============================] - 0s 6ms/step - loss: 28.5588
Epoch 7/500
1/1 [==============================] - 0s 11ms/step - loss: 27.7488
Epoch 8/500
1/1 [==============================] - 0s 9ms/step - loss: 26.9484
Epoch 9/500
1/1 [==============================] - 0s 8ms/step - loss: 26.1554
Epoch 10/500
1/1 [==============================] - 0s 8ms/step - loss: 25.3673
Epoch 11/500
1/1 [==============================] - 0s 9ms/step - loss: 24.5822
Epoch 12/500
1/1 [==============================] - 0s 7ms/step - loss: 23.7987
Epoch 13/500
1/1 [==============================

In [13]:
 model.predict(np.array([5,6,7]).reshape(1,3,1))

1/1 [==============================] - 0s 263ms/step


array([[7.8478503]], dtype=float32)

# 2. Many to Many

In [20]:
X = np.array([x for x in range(5, 301, 5)]).reshape(20,3,1)
Y = np.array([y for y in range(20, 316,5)]).reshape(20,3,1)

In [21]:
X

array([[[  5],
        [ 10],
        [ 15]],

       [[ 20],
        [ 25],
        [ 30]],

       [[ 35],
        [ 40],
        [ 45]],

       [[ 50],
        [ 55],
        [ 60]],

       [[ 65],
        [ 70],
        [ 75]],

       [[ 80],
        [ 85],
        [ 90]],

       [[ 95],
        [100],
        [105]],

       [[110],
        [115],
        [120]],

       [[125],
        [130],
        [135]],

       [[140],
        [145],
        [150]],

       [[155],
        [160],
        [165]],

       [[170],
        [175],
        [180]],

       [[185],
        [190],
        [195]],

       [[200],
        [205],
        [210]],

       [[215],
        [220],
        [225]],

       [[230],
        [235],
        [240]],

       [[245],
        [250],
        [255]],

       [[260],
        [265],
        [270]],

       [[275],
        [280],
        [285]],

       [[290],
        [295],
        [300]]])

In [22]:
Y

array([[[ 20],
        [ 25],
        [ 30]],

       [[ 35],
        [ 40],
        [ 45]],

       [[ 50],
        [ 55],
        [ 60]],

       [[ 65],
        [ 70],
        [ 75]],

       [[ 80],
        [ 85],
        [ 90]],

       [[ 95],
        [100],
        [105]],

       [[110],
        [115],
        [120]],

       [[125],
        [130],
        [135]],

       [[140],
        [145],
        [150]],

       [[155],
        [160],
        [165]],

       [[170],
        [175],
        [180]],

       [[185],
        [190],
        [195]],

       [[200],
        [205],
        [210]],

       [[215],
        [220],
        [225]],

       [[230],
        [235],
        [240]],

       [[245],
        [250],
        [255]],

       [[260],
        [265],
        [270]],

       [[275],
        [280],
        [285]],

       [[290],
        [295],
        [300]],

       [[305],
        [310],
        [315]]])

In [25]:
model = Sequential()
model.add(LSTM(64, activation = 'tanh', input_shape = (3,1), return_sequences = True)) # return_sequences = True
model.add(Dense(32))
model.add(Dense(16))
model.add(TimeDistributed(Dense(1))) # timestep별로 정답을 매칭 시켜줌 ㅇㅇ
model.compile(loss = 'mse', optimizer = 'adam')

In [26]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_3 (LSTM)               (None, 3, 64)             16896     
                                                                 
 dense_6 (Dense)             (None, 3, 32)             2080      
                                                                 
 dense_7 (Dense)             (None, 3, 16)             528       
                                                                 
 time_distributed_1 (TimeDi  (None, 3, 1)              17        
 stributed)                                                      
                                                                 
Total params: 19521 (76.25 KB)
Trainable params: 19521 (76.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [27]:
model.fit(X,Y, epochs = 1000)

Epoch 1/1000
1/1 [==============================] - 2s 2s/step - loss: 35298.2383
Epoch 2/1000
1/1 [==============================] - 0s 16ms/step - loss: 35228.0508
Epoch 3/1000
1/1 [==============================] - 0s 8ms/step - loss: 35157.2578
Epoch 4/1000
1/1 [==============================] - 0s 1ms/step - loss: 35086.1328
Epoch 5/1000
1/1 [==============================] - 0s 15ms/step - loss: 35014.8672
Epoch 6/1000
1/1 [==============================] - 0s 0s/step - loss: 34943.5586
Epoch 7/1000
1/1 [==============================] - 0s 4ms/step - loss: 34872.2344
Epoch 8/1000
1/1 [==============================] - 0s 14ms/step - loss: 34800.8984
Epoch 9/1000
1/1 [==============================] - 0s 699us/step - loss: 34729.5156
Epoch 10/1000
1/1 [==============================] - 0s 18ms/step - loss: 34658.0352
Epoch 11/1000
1/1 [==============================] - 0s 12ms/step - loss: 34586.3438
Epoch 12/1000
1/1 [==============================] - 0s 2ms/step - loss: 34513.8

In [28]:
model.predict(np.array([300,305,310]).reshape(1,3,1))

1/1 [==============================] - 0s 383ms/step


array([[[301.57852],
        [320.3311 ],
        [325.80087]]], dtype=float32)