In [21]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer, text_to_word_sequence
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.layers import Dense, SimpleRNN, Embedding, LSTM
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam

In [22]:
text = '''하늘에서 오늘 눈이 내리고 있다
그의 눈이 예쁘다
그는 오늘 공부를 한다'''

In [23]:
t = Tokenizer()
t.fit_on_texts( [text]) # list of string

In [24]:
t.word_index

{'오늘': 1,
 '눈이': 2,
 '하늘에서': 3,
 '내리고': 4,
 '있다': 5,
 '그의': 6,
 '예쁘다': 7,
 '그는': 8,
 '공부를': 9,
 '한다': 10}

In [25]:
text_to_word_sequence( text )

['하늘에서', '오늘', '눈이', '내리고', '있다', '그의', '눈이', '예쁘다', '그는', '오늘', '공부를', '한다']

In [26]:
# text_to_word_sequence( text )
s = text.split('\n')
s

['하늘에서 오늘 눈이 내리고 있다', '그의 눈이 예쁘다', '그는 오늘 공부를 한다']

In [27]:
sentences = []
for line in s:
    print("line:", line)
    encoded = t.texts_to_sequences( [line] )[0]
    print("encoded", encoded)
    for i in range(1, len(encoded) ):
        sentence = encoded[:i+1]
        sentences.append( sentence )
print( sentences )

line: 하늘에서 오늘 눈이 내리고 있다
encoded [3, 1, 2, 4, 5]
line: 그의 눈이 예쁘다
encoded [6, 2, 7]
line: 그는 오늘 공부를 한다
encoded [8, 1, 9, 10]
[[3, 1], [3, 1, 2], [3, 1, 2, 4], [3, 1, 2, 4, 5], [6, 2], [6, 2, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10]]


In [28]:
sentences

[[3, 1],
 [3, 1, 2],
 [3, 1, 2, 4],
 [3, 1, 2, 4, 5],
 [6, 2],
 [6, 2, 7],
 [8, 1],
 [8, 1, 9],
 [8, 1, 9, 10]]

In [29]:
textData = pad_sequences( sentences)

In [30]:
textData

array([[ 0,  0,  0,  3,  1],
       [ 0,  0,  3,  1,  2],
       [ 0,  3,  1,  2,  4],
       [ 3,  1,  2,  4,  5],
       [ 0,  0,  0,  6,  2],
       [ 0,  0,  6,  2,  7],
       [ 0,  0,  0,  8,  1],
       [ 0,  0,  8,  1,  9],
       [ 0,  8,  1,  9, 10]])

In [31]:
x = textData[:,:-1]

In [32]:
y = textData[:,[-1] ]

In [33]:
y.shape

(9, 1)

In [34]:
x

array([[0, 0, 0, 3],
       [0, 0, 3, 1],
       [0, 3, 1, 2],
       [3, 1, 2, 4],
       [0, 0, 0, 6],
       [0, 0, 6, 2],
       [0, 0, 0, 8],
       [0, 0, 8, 1],
       [0, 8, 1, 9]])

In [35]:
x.reshape(-1,4,1)

array([[[0],
        [0],
        [0],
        [3]],

       [[0],
        [0],
        [3],
        [1]],

       [[0],
        [3],
        [1],
        [2]],

       [[3],
        [1],
        [2],
        [4]],

       [[0],
        [0],
        [0],
        [6]],

       [[0],
        [0],
        [6],
        [2]],

       [[0],
        [0],
        [0],
        [8]],

       [[0],
        [0],
        [8],
        [1]],

       [[0],
        [8],
        [1],
        [9]]])

In [36]:
model = Sequential()
model.add( LSTM(32, activation='relu', input_shape=(4,1)))
model.add( Dense(11, activation='softmax') )
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam',
             metrics=['accuracy'])
model.fit( x.reshape(-1,4,1), y , epochs=500)

Epoch 1/500
1/1 [==============================] - 1s 962ms/step - loss: 2.4609 - accuracy: 0.1111
Epoch 2/500
1/1 [==============================] - 0s 4ms/step - loss: 2.4530 - accuracy: 0.1111
Epoch 3/500
1/1 [==============================] - 0s 16ms/step - loss: 2.4454 - accuracy: 0.1111
Epoch 4/500
1/1 [==============================] - 0s 0s/step - loss: 2.4378 - accuracy: 0.1111
Epoch 5/500
1/1 [==============================] - 0s 17ms/step - loss: 2.4304 - accuracy: 0.1111
Epoch 6/500
1/1 [==============================] - 0s 0s/step - loss: 2.4232 - accuracy: 0.1111
Epoch 7/500
1/1 [==============================] - 0s 17ms/step - loss: 2.4160 - accuracy: 0.1111
Epoch 8/500
1/1 [==============================] - 0s 16ms/step - loss: 2.4089 - accuracy: 0.1111
Epoch 9/500
1/1 [==============================] - 0s 0s/step - loss: 2.4019 - accuracy: 0.1111
Epoch 10/500
1/1 [==============================] - 0s 17ms/step - loss: 2.3951 - accuracy: 0.1111
Epoch 11/500
1/1 [=======

In [39]:
from tensorflow.keras.utils import to_categorical

In [41]:
y_enc = to_categorical( y )

In [43]:
y_enc

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [44]:
y

array([[ 1],
       [ 2],
       [ 4],
       [ 5],
       [ 2],
       [ 7],
       [ 1],
       [ 9],
       [10]])

In [42]:
y_enc.shape

(9, 11)

In [17]:
enc = t.texts_to_sequences(['하늘에서 오늘'])
enc

[[3, 1]]

In [18]:
p = pad_sequences( enc ,4)
p

array([[0, 0, 3, 1]])

In [37]:
model.predict( p.reshape(1,4,1) )

1/1 [==============================] - 0s 182ms/step


array([[8.2670081e-27, 1.9569616e-04, 9.9976426e-01, 5.8908792e-20,
        4.8395327e-06, 1.6118477e-12, 6.8435198e-23, 3.5152170e-05,
        9.3025980e-23, 5.3831497e-12, 1.3529152e-16]], dtype=float32)

In [19]:
model.predict( p.reshape(1,4,1) ).argmax(axis=1)

1/1 [==============================] - 0s 171ms/step


array([2], dtype=int64)